name: Deploy React-Vite LandingPage-KOLevent app

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠️ Build project with Vite
        run: npm run build

      - name: 📂 Prepare server folder for deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: abp-server4
          key: ${{secrets.SSH_RSA_KEY}}
          script: |
            rm -rf /usr/share/nginx/landingpage-kolevent
            mkdir -p /usr/share/nginx/landingpage-kolevent

      - name: 🚀 Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: abp-server4
          key: ${{ secrets.SSH_RSA_KEY }}
          source: 'dist/**'
          target: '/usr/share/nginx/landingpage-kolevent'
          strip_components: 1
